### Test: Chiamata al webhook /create-pre-orders
POST http://localhost:8080/api/verify-multi-pre-order-payment-stablecoin
Content-Type: application/json
Authorization: Bearer your_jwt_token_here

{
  "order_id": "29977-044218-7626",
  "basket_ids": ["6247-425004-9809","6247-425004-9807"]
}
