app = "smartdropper-dev"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true          # ✅ Spegni se inattiva
  auto_start_machines = true         # ✅ Riaccendi se serve
  min_machines_running = 0           # ✅ Nessuna macchina fissa
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.http_api_health]
    grace_period = "15s"
    interval = "10s"
    method = "get"
    path = "/api/health"
    port = 8080
    timeout = "5s"
    type = "http"
