# fly.toml app configuration file generated for web3 on 2025-06-12T20:04:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web3-bold-sea-5098'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1