app = 'web3-bold-sea-5098'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[services.http_checks]]
  interval = "15s"
  timeout = "5s"
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http"
