### Inserimento dati nella tabella subscription
#POST  https://api.smartdropper.io/web3/verify-subscription-payment
# POST  http://localhost:4000/api/verify-subscription-payment
POST  http://localhost:4000/api/verify-subscription-payment
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyMywiZW1haWwiOiJ1c2VyQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIn0.JdBB91sQCX5cnczZn4hfm9ztKJijsUNMYsbC1PLEKhQ
Content-Type: application/json

{
  "wallet": "0x39AF390FC9FDef3e550475F12aF47D65B517FEcD",
  "payment_tx": "0x9993bdbe5855813bd2a44a1a7d0c7ad835216441769d44e06733a9e7acb0c0b7",
  "amount_paid": "7.78",
  "status": "CONFIRMING",
  "created_at": "2025-03-01 19:04:07.454216+00"
}
